import type { Product } from "@/types/product";

export const healthcareCategoryProducts: Product[] = [
  {
    id: 101,
    slug: "medicare-plus-hospital",
    name: "MediCare Plus Hospital",
    category: "hospital",
    subCategoryLabel: "Hospital & Clinic",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 60,
    img: "/images/templates.jpg",
    alt: "MediCare Plus Hospital Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "156",
    rating: "4.8",
    tags: [
      "Appointment Booking",
      "Doctor Profiles",
      "WhatsApp",
      "SEO",
    ],
  },
  {
    id: 102,
    slug: "smilecare-dental",
    name: "SmileCare Dental Studio",
    category: "dental-clinic",
    subCategoryLabel: "Dental Hospital",
    price: 9999,
    priceDisplay: "₹9,999",
    priceTier: "Up to 20 Pages",
    discount: 55,
    img: "/images/templates.jpg",
    alt: "SmileCare Dental Hospital Website",
    previewUrl: "https://themedekho.com/",
    badges: [],
    sold: "98",
    rating: "4.7",
    tags: [
      "Appointment Booking",
      "Treatments",
      "Doctor Profiles",
      "WhatsApp",
    ],
  },
  {
    id: 103,
    slug: "visionpoint-eye-clinic",
    name: "VisionPoint Eye Clinic",
    category: "eye-hospital",
    subCategoryLabel: "Eye Hospital",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 25 Pages",
    discount: 58,
    img: "/images/templates.jpg",
    alt: "VisionPoint Eye Hospital Website",
    previewUrl: "https://themedekho.com/",
    badges: [],
    sold: "76",
    rating: "4.6",
    tags: [
      "Appointment Booking",
      "Doctor Profiles",
      "Treatments",
      "Inquiry Form",
    ],
  },

  {
  id: 104,
  slug: "heartcare-cardiology",
  name: "HeartCare Cardiology Center",
  category: "cardiology",
  subCategoryLabel: "Cardiology",
  price: 15999,
  priceDisplay: "₹15,999",
  priceTier: "Up to 30 Pages",
  discount: 60,
  img: "/images/templates.jpg",
  alt: "HeartCare Cardiology Website",
  previewUrl: "https://themedekho.com/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "84",
  rating: "4.8",
  tags: [
    "Appointment Booking",
    "Doctor Profiles",
    "Cardiac Treatments",
    "WhatsApp",
  ],
},

{
  id: 105,
  slug: "dr-healthcare-profile",
  name: "Dr. Healthcare Profile",
  category: "doctor",
  subCategoryLabel: "Doctor",
  price: 7999,
  priceDisplay: "₹7,999",
  priceTier: "Up to 12 Pages",
  discount: 50,
  img: "/images/templates.jpg",
  alt: "Doctor Portfolio Website",
  previewUrl: "https://themedekho.com/",
  badges: [],
  sold: "61",
  rating: "4.6",
  tags: [
    "Doctor Profile",
    "Appointment Booking",
    "Treatments",
    "Contact Form",
  ],
},

{
  id: 106,
  slug: "medtour-global",
  name: "MedTour Global",
  category: "medical-tourism",
  subCategoryLabel: "Medical Tourism",
  price: 19999,
  priceDisplay: "₹19,999",
  priceTier: "Up to 40 Pages",
  discount: 62,
  img: "/images/templates.jpg",
  alt: "Medical Tourism Website",
  previewUrl: "https://themedekho.com/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "134",
  rating: "4.9",
  tags: [
    "International Patients",
    "Hospital Directory",
    "Visa Assistance",
    "Treatment Inquiry",
  ],
},

{
  id: 107,
  slug: "citycare-hospital",
  name: "CityCare Multispeciality Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 17999,
  priceDisplay: "₹17,999",
  priceTier: "Up to 35 Pages",
  discount: 61,
  img: "/images/templates.jpg",
  alt: "CityCare Multispeciality Hospital Website",
  previewUrl: "https://themedekho.com/",
  badges: [],
  sold: "119",
  rating: "4.8",
  tags: [
    "Doctor Directory",
    "Departments",
    "Appointment Booking",
    "Emergency Contact",
  ],
},

{
  id: 108,
  slug: "bright-smile-dental",
  name: "Bright Smile Dental Hospital",
  category: "dental-clinic",
  subCategoryLabel: "Dental Hospital",
  price: 11999,
  priceDisplay: "₹11,999",
  priceTier: "Up to 20 Pages",
  discount: 57,
  img: "/images/templates.jpg",
  alt: "Bright Smile Dental Hospital Website",
  previewUrl: "https://themedekho.com/",
  badges: [],
  sold: "72",
  rating: "4.7",
  tags: [
    "Dental Treatments",
    "Appointment Booking",
    "Before After Gallery",
    "WhatsApp",
  ],
},

{
  id: 109,
  slug: "vision-eye-care",
  name: "Vision Eye Care Center",
  category: "eye-hospital",
  subCategoryLabel: "Eye Hospital",
  price: 13999,
  priceDisplay: "₹13,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/templates.jpg",
  alt: "Vision Eye Care Center Website",
  previewUrl: "https://themedekho.com/",
  badges: [],
  sold: "88",
  rating: "4.8",
  tags: [
    "Eye Treatments",
    "Doctor Profiles",
    "Appointment Booking",
    "Patient Inquiry",
  ],
},
];