import type { Product } from "@/types/product";
export const healthcareCategoryProducts: Product[] = [
  {
    id: 101,
    slug: "medicare-plus-hospital",
    name: "MediCare Plus Hospital",
    category: "hospital",
    subCategoryLabel: "Hospital & Clinic",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 60,
    img: "/images/templates/healthcare/hospital1.webp",
    alt: "MediCare Plus Hospital Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "156",
    rating: "4.8",
    tags: [
      "Appointment Booking",
      "Doctor Profiles",
      "WhatsApp",
      "SEO",
    ],
  },
  {
    id: 102,
    slug: "smilecare-dental",
    name: "SmileCare Dental Studio",
    category: "dental-clinic",
    subCategoryLabel: "Dental Hospital",
    price: 9999,
    priceDisplay: "₹9,999",
    priceTier: "Up to 20 Pages",
    discount: 55,
    img: "/images/templates/healthcare/dental1.webp",
    alt: "SmileCare Dental Hospital Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "98",
    rating: "4.7",
    tags: [
      "Appointment Booking",
      "Treatments",
      "Doctor Profiles",
      "WhatsApp",
    ],
  },
  {
    id: 103,
    slug: "visionpoint-eye-clinic",
    name: "VisionPoint Eye Clinic",
    category: "eye-hospital",
    subCategoryLabel: "Eye Hospital",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 25 Pages",
    discount: 58,
    img: "/images/templates/healthcare/eye1.webp",
    alt: "VisionPoint Eye Hospital Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "76",
    rating: "4.6",
    tags: [
      "Appointment Booking",
      "Doctor Profiles",
      "Treatments",
      "Inquiry Form",
    ],
  },

  {
  id: 104,
  slug: "heartcare-cardiology",
  name: "HeartCare Cardiology Center",
  category: "cardiology",
  subCategoryLabel: "Cardiology",
  price: 15999,
  priceDisplay: "₹15,999",
  priceTier: "Up to 30 Pages",
  discount: 60,
  img: "/images/templates/healthcare/cardio3.webp",
  alt: "HeartCare Cardiology Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "84",
  rating: "4.8",
  tags: [
    "Appointment Booking",
    "Doctor Profiles",
    "Cardiac Treatments",
    "WhatsApp",
  ],
},

{
  id: 105,
  slug: "dr-healthcare-profile",
  name: "Dr. Healthcare Profile",
  category: "doctor",
  subCategoryLabel: "Doctor",
  price: 7999,
  priceDisplay: "₹7,999",
  priceTier: "Up to 12 Pages",
  discount: 50,
  img: "/images/theme.webp",
  alt: "Doctor Portfolio Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "61",
  rating: "4.6",
  tags: [
    "Doctor Profile",
    "Appointment Booking",
    "Treatments",
    "Contact Form",
  ],
},

{
  id: 106,
  slug: "medtour-global",
  name: "MedTour Global",
  category: "medical-tourism",
  subCategoryLabel: "Medical Tourism",
  price: 19999,
  priceDisplay: "₹19,999",
  priceTier: "Up to 40 Pages",
  discount: 62,
  img: "/images/theme.webp",
  alt: "Medical Tourism Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "134",
  rating: "4.9",
  tags: [
    "International Patients",
    "Hospital Directory",
    "Visa Assistance",
    "Treatment Inquiry",
  ],
},

{
  id: 107,
  slug: "citycare-hospital",
  name: "CityCare Multispeciality Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 17999,
  priceDisplay: "₹17,999",
  priceTier: "Up to 35 Pages",
  discount: 61,
  img: "/images/templates/healthcare/hospital2.webp",
  alt: "CityCare Multispeciality Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "119",
  rating: "4.8",
  tags: [
    "Doctor Directory",
    "Departments",
    "Appointment Booking",
    "Emergency Contact",
  ],
},

{
  id: 108,
  slug: "bright-smile-dental",
  name: "Bright Smile Dental Hospital",
  category: "dental-clinic",
  subCategoryLabel: "Dental Hospital",
  price: 11999,
  priceDisplay: "₹11,999",
  priceTier: "Up to 20 Pages",
  discount: 57,
  img: "/images/templates/healthcare/dental2.webp",
  alt: "Bright Smile Dental Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "72",
  rating: "4.7",
  tags: [
    "Dental Treatments",
    "Appointment Booking",
    "Before After Gallery",
    "WhatsApp",
  ],
},

{
  id: 109,
  slug: "vision-eye-care",
  name: "Vision Eye Care Center",
  category: "eye-hospital",
  subCategoryLabel: "Eye Hospital",
  price: 13999,
  priceDisplay: "₹13,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/templates/healthcare/eye2.webp",
  alt: "Vision Eye Care Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "88",
  rating: "4.8",
  tags: [
    "Eye Treatments",
    "Doctor Profiles",
    "Appointment Booking",
    "Patient Inquiry",
  ],
    },

  {
  id: 110,
  slug: "lifeline-super-speciality-hospital",
  name: "Lifeline Super Speciality Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 18999,
  priceDisplay: "₹18,999",
  priceTier: "Up to 35 Pages",
  discount: 62,
  img: "/images/templates/healthcare/hospital3.webp",
  alt: "Lifeline Super Speciality Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "143",
  rating: "4.8",
  tags: [
    "Departments",
    "Doctor Directory",
    "Appointment Booking",
    "Emergency Contact",
  ],
},

{
  id: 111,
  slug: "apollo-care-hospital",
  name: "Apollo Care Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 16999,
  priceDisplay: "₹16,999",
  priceTier: "Up to 30 Pages",
  discount: 59,
  img: "/images/templates/healthcare/hospital4.webp",
  alt: "Apollo Care Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "128",
  rating: "4.7",
  tags: [
    "Doctor Profiles",
    "Departments",
    "Patient Inquiry",
    "WhatsApp",
  ],
},

{
  id: 112,
  slug: "greenfield-hospital",
  name: "Greenfield Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 15999,
  priceDisplay: "₹15,999",
  priceTier: "Up to 30 Pages",
  discount: 58,
  img: "/images/templates/healthcare/hospital5.webp",
  alt: "Greenfield Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "96",
  rating: "4.7",
  tags: [
    "Appointment Booking",
    "Emergency Services",
    "Doctor Directory",
    "Testimonials",
  ],
},

{
  id: 113,
  slug: "metro-health-hospital",
  name: "Metro Health Hospital",
  category: "hospital",
  subCategoryLabel: "Hospital & Clinic",
  price: 19999,
  priceDisplay: "₹19,999",
  priceTier: "Up to 40 Pages",
  discount: 63,
  img: "/images/templates/healthcare/hospital6.webp",
  alt: "Metro Health Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "171",
  rating: "4.9",
  tags: [
    "Departments",
    "Doctor Directory",
    "Appointment Booking",
    "CRM",
  ],
},

{
  id: 114,
  slug: "dental-care-plus",
  name: "Dental Care Plus",
  category: "dental-clinic",
  subCategoryLabel: "Dental Clinic",
  price: 10999,
  priceDisplay: "₹10,999",
  priceTier: "Up to 20 Pages",
  discount: 55,
  img: "/images/templates/healthcare/dental3.webp",
  alt: "Dental Care Plus Clinic Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "67",
  rating: "4.7",
  tags: [
    "Dental Treatments",
    "Appointment Booking",
    "Doctor Profiles",
    "WhatsApp",
  ],
},

{
  id: 115,
  slug: "perfect-smile-dental",
  name: "Perfect Smile Dental Clinic",
  category: "dental-clinic",
  subCategoryLabel: "Dental Clinic",
  price: 12999,
  priceDisplay: "₹12,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/templates/healthcare/dental4.webp",
  alt: "Perfect Smile Dental Clinic Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "104",
  rating: "4.8",
  tags: [
    "Treatment Pages",
    "Before After Gallery",
    "Appointment Booking",
    "Patient Reviews",
  ],
},

{
  id: 116,
  slug: "smile-point-dental",
  name: "Smile Point Dental Center",
  category: "dental-clinic",
  subCategoryLabel: "Dental Clinic",
  price: 8999,
  priceDisplay: "₹8,999",
  priceTier: "Up to 15 Pages",
  discount: 50,
  img: "/images/templates/healthcare/dental5.webp",
  alt: "Smile Point Dental Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "54",
  rating: "4.6",
  tags: [
    "Dentist Profiles",
    "Appointment Booking",
    "Services",
    "Contact Form",
  ],
},

{
  id: 117,
  slug: "clearvision-eye-hospital",
  name: "ClearVision Eye Hospital",
  category: "eye-hospital",
  subCategoryLabel: "Eye Hospital",
  price: 14999,
  priceDisplay: "₹14,999",
  priceTier: "Up to 25 Pages",
  discount: 59,
  img: "/images/templates/healthcare/eye3.webp",
  alt: "ClearVision Eye Hospital Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "93",
  rating: "4.8",
  tags: [
    "Eye Treatments",
    "Doctor Profiles",
    "Appointment Booking",
    "Patient Reviews",
  ],
},

{
  id: 118,
  slug: "advanced-eye-centre",
  name: "Advanced Eye Centre",
  category: "eye-hospital",
  subCategoryLabel: "Eye Hospital",
  price: 11999,
  priceDisplay: "₹11,999",
  priceTier: "Up to 20 Pages",
  discount: 56,
  img: "/images/templates/healthcare/eye4.webp",
  alt: "Advanced Eye Centre Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "69",
  rating: "4.7",
  tags: [
    "Eye Specialists",
    "Treatment Pages",
    "Appointment Booking",
    "WhatsApp",
  ],
},

{
  id: 119,
  slug: "cardio-life-heart-centre",
  name: "CardioLife Heart Centre",
  category: "cardiology",
  subCategoryLabel: "Cardiology",
  price: 16999,
  priceDisplay: "₹16,999",
  priceTier: "Up to 30 Pages",
  discount: 60,
  img: "/images/templates/healthcare/cardio2.webp",
  alt: "CardioLife Heart Centre Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "92",
  rating: "4.8",
  tags: [
    "Cardiologist Profiles",
    "Appointment Booking",
    "Heart Treatments",
    "Patient Reviews",
  ],
},

{
  id: 120,
  slug: "heart-first-cardiac-clinic",
  name: "Heart First Cardiac Clinic",
  category: "cardiology",
  subCategoryLabel: "Cardiology",
  price: 13999,
  priceDisplay: "₹13,999",
  priceTier: "Up to 25 Pages",
  discount: 57,
  img: "/images/templates/healthcare/cardio1.webp",
  alt: "Heart First Cardiac Clinic Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "73",
  rating: "4.7",
  tags: [
    "Cardiac Services",
    "Doctor Profiles",
    "Appointment Booking",
    "WhatsApp",
  ],
},

{
  id: 121,
  slug: "pulse-heart-institute",
  name: "Pulse Heart Institute",
  category: "cardiology",
  subCategoryLabel: "Cardiology",
  price: 18999,
  priceDisplay: "₹18,999",
  priceTier: "Up to 35 Pages",
  discount: 62,
  img: "/images/templates/healthcare/cardio4.webp",
  alt: "Pulse Heart Institute Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "116",
  rating: "4.9",
  tags: [
    "Heart Treatments",
    "Cardiologist Directory",
    "Appointment Booking",
    "CRM",
  ],
},

{
  id: 122,
  slug: "dr-arjun-clinic",
  name: "Dr. Arjun Clinic",
  category: "doctor",
  subCategoryLabel: "Doctor",
  price: 8999,
  priceDisplay: "₹8,999",
  priceTier: "Up to 15 Pages",
  discount: 52,
  img: "/images/theme.webp",
  alt: "Doctor Clinic Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "58",
  rating: "4.6",
  tags: [
    "Doctor Profile",
    "Appointment Booking",
    "Services",
    "Contact Form",
  ],
},

{
  id: 123,
  slug: "specialist-doctor-profile",
  name: "Specialist Doctor Profile",
  category: "doctor",
  subCategoryLabel: "Doctor",
  price: 10999,
  priceDisplay: "₹10,999",
  priceTier: "Up to 20 Pages",
  discount: 55,
  img: "/images/theme.webp",
  alt: "Specialist Doctor Portfolio Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "74",
  rating: "4.7",
  tags: [
    "Doctor Profile",
    "Treatments",
    "Appointment Booking",
    "Patient Reviews",
  ],
},

{
  id: 124,
  slug: "premium-doctor-portfolio",
  name: "Premium Doctor Portfolio",
  category: "doctor",
  subCategoryLabel: "Doctor",
  price: 12999,
  priceDisplay: "₹12,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/theme.webp",
  alt: "Premium Doctor Portfolio Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "91",
  rating: "4.8",
  tags: [
    "Doctor Profile",
    "Treatment Pages",
    "Appointment Booking",
    "WhatsApp",
  ],
},

{
  id: 125,
  slug: "hope-ivf-center",
  name: "Hope IVF Center",
  category: "ivf-center",
  subCategoryLabel: "IVF Center",
  price: 14999,
  priceDisplay: "₹14,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/theme.webp",
  alt: "Hope IVF Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "86",
  rating: "4.8",
  tags: [
    "IVF Treatments",
    "Doctor Profiles",
    "Appointment Booking",
    "Patient Inquiry",
  ],
},

{
  id: 126,
  slug: "fertility-care-ivf",
  name: "Fertility Care IVF",
  category: "ivf-center",
  subCategoryLabel: "IVF Center",
  price: 16999,
  priceDisplay: "₹16,999",
  priceTier: "Up to 30 Pages",
  discount: 60,
  img: "/images/theme.webp",
  alt: "Fertility Care IVF Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "108",
  rating: "4.8",
  tags: [
    "IVF Services",
    "Success Stories",
    "Doctor Profiles",
    "WhatsApp",
  ],
},

{
  id: 127,
  slug: "motherhood-fertility-center",
  name: "Motherhood Fertility Center",
  category: "ivf-center",
  subCategoryLabel: "IVF Center",
  price: 18999,
  priceDisplay: "₹18,999",
  priceTier: "Up to 35 Pages",
  discount: 62,
  img: "/images/theme.webp",
  alt: "Motherhood Fertility Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "121",
  rating: "4.9",
  tags: [
    "IVF Treatments",
    "International Patients",
    "Appointment Booking",
    "CRM",
  ],
},

{
  id: 128,
  slug: "newlife-ivf-clinic",
  name: "NewLife IVF Clinic",
  category: "ivf-center",
  subCategoryLabel: "IVF Center",
  price: 12999,
  priceDisplay: "₹12,999",
  priceTier: "Up to 20 Pages",
  discount: 56,
  img: "/images/theme.webp",
  alt: "NewLife IVF Clinic Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "64",
  rating: "4.7",
  tags: [
    "Fertility Treatments",
    "Doctor Profiles",
    "Appointment Booking",
    "Testimonials",
  ],
},

{
  id: 129,
  slug: "healthscan-diagnostics",
  name: "HealthScan Diagnostic Center",
  category: "diagnostic-center",
  subCategoryLabel: "Diagnostic Center",
  price: 11999,
  priceDisplay: "₹11,999",
  priceTier: "Up to 20 Pages",
  discount: 56,
  img: "/images/theme.webp",
  alt: "HealthScan Diagnostic Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "82",
  rating: "4.7",
  tags: [
    "Lab Tests",
    "Health Packages",
    "Online Booking",
    "Report Inquiry",
  ],
},

{
  id: 130,
  slug: "prime-diagnostics",
  name: "Prime Diagnostics",
  category: "diagnostic-center",
  subCategoryLabel: "Diagnostic Center",
  price: 13999,
  priceDisplay: "₹13,999",
  priceTier: "Up to 25 Pages",
  discount: 58,
  img: "/images/theme.webp",
  alt: "Prime Diagnostics Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "105",
  rating: "4.8",
  tags: [
    "Pathology Tests",
    "Diagnostic Packages",
    "Home Sample Collection",
    "WhatsApp",
  ],
},

{
  id: 131,
  slug: "medilab-diagnostic-center",
  name: "MediLab Diagnostic Center",
  category: "diagnostic-center",
  subCategoryLabel: "Diagnostic Center",
  price: 9999,
  priceDisplay: "₹9,999",
  priceTier: "Up to 18 Pages",
  discount: 54,
  img: "/images/theme.webp",
  alt: "MediLab Diagnostic Center Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "66",
  rating: "4.6",
  tags: [
    "Blood Tests",
    "Radiology",
    "Online Booking",
    "Contact Form",
  ],
},

{
  id: 132,
  slug: "accurate-diagnostics",
  name: "Accurate Diagnostics",
  category: "diagnostic-center",
  subCategoryLabel: "Diagnostic Center",
  price: 14999,
  priceDisplay: "₹14,999",
  priceTier: "Up to 28 Pages",
  discount: 59,
  img: "/images/theme.webp",
  alt: "Accurate Diagnostics Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "91",
  rating: "4.8",
  tags: [
    "Diagnostic Tests",
    "Health Packages",
    "Home Collection",
    "Report Download",
  ],
},

{
  id: 133,
  slug: "advanced-diagnostic-lab",
  name: "Advanced Diagnostic Lab",
  category: "diagnostic-center",
  subCategoryLabel: "Diagnostic Center",
  price: 16999,
  priceDisplay: "₹16,999",
  priceTier: "Up to 30 Pages",
  discount: 61,
  img: "/images/theme.webp",
  alt: "Advanced Diagnostic Lab Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "118",
  rating: "4.9",
  tags: [
    "Lab Tests",
    "Radiology",
    "Health Packages",
    "CRM Integration",
  ],
},

{
  id: 134,
  slug: "india-medical-journey",
  name: "India Medical Journey",
  category: "medical-tourism",
  subCategoryLabel: "Medical Tourism",
  price: 21999,
  priceDisplay: "₹21,999",
  priceTier: "Up to 40 Pages",
  discount: 63,
  img: "/images/theme.webp",
  alt: "India Medical Journey Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [],
  sold: "97",
  rating: "4.8",
  tags: [
    "International Patients",
    "Hospital Network",
    "Visa Assistance",
    "Treatment Inquiry",
  ],
},

{
  id: 135,
  slug: "global-health-travel",
  name: "Global Health Travel",
  category: "medical-tourism",
  subCategoryLabel: "Medical Tourism",
  price: 24999,
  priceDisplay: "₹24,999",
  priceTier: "Up to 45 Pages",
  discount: 65,
  img: "/images/theme.webp",
  alt: "Global Health Travel Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-hot",
      label: "Popular",
    },
  ],
  sold: "126",
  rating: "4.9",
  tags: [
    "International Patients",
    "Treatment Packages",
    "Hospital Directory",
    "Airport Assistance",
  ],
},

{
  id: 136,
  slug: "medassist-india",
  name: "MedAssist India",
  category: "medical-tourism",
  subCategoryLabel: "Medical Tourism",
  price: 18999,
  priceDisplay: "₹18,999",
  priceTier: "Up to 35 Pages",
  discount: 61,
  img: "/images/theme.webp",
  alt: "MedAssist India Medical Tourism Website",
  previewUrl: "https://theme-dekho.github.io/development_page/",
  badges: [
    {
      type: "badge-premium",
      label: "Premium",
    },
  ],
  sold: "89",
  rating: "4.8",
  tags: [
    "Medical Visa",
    "Treatment Inquiry",
    "Hospital Partners",
    "Patient Support",
  ],
},
];