import type { Product } from "@/types/product";

export const interiorProducts: Product[] = [
  {
    id: 1,
    slug: "decorpot",
    name: "Decorpot",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 68,
    img: "/images/templates/interior/decorpot.jpg",
    alt: "Decorpot Interior Design Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-sale",
        label: "68% Off",
      },
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "98",
    rating: "4.8",
    tags: [
      "AI Chat Bot",
      "CRM",
      "Price Calculator",
      "BOQ",
    ],
  },
  {
    id: 2,
    slug: "gopesh-interior",
    name: "Gopesh Interior Furniture House",
    category: "interior-firm",
    subCategoryLabel: "Interior & Furniture",
    price: 9999,
    priceDisplay: "₹9,999",
    priceTier: "Up to 15 Pages",
    discount: 55,
    img: "/images/templates/interior/gopesh-interior.jpg",
    alt: "Gopesh Interior Furniture House Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "33",
    rating: "4.5",
    tags: [
      "AI Chat Bot",
      "CRM",
      "Price Calculator",
      "BOQ",
    ],
  },
  {
    id: 3,
    slug: "modern-architect-studio",
    name: "Modern Architect Studio",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 19999,
    priceDisplay: "₹19,999",
    priceTier: "Up to 40 Pages",
    discount: 61,
    img: "/images/templates/interior/modern-architect.jpg",
    alt: "Modern Architecture Studio Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "67",
    rating: "4.9",
    tags: [
      "Project Gallery",
      "CRM",
      "Lead Form",
      "SEO",
    ],
  },
  {
    id: 4,
    slug: "interior-portfolio-pro",
    name: "Interior Portfolio Pro",
    category: "interior-portfolio",
    subCategoryLabel: "Interior Designer Portfolio",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 20 Pages",
    discount: 58,
    img: "/images/templates/interior/interior-portfolio.jpg",
    alt: "Interior Designer Portfolio Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-new",
        label: "New",
      },
    ],
    sold: "41",
    rating: "4.7",
    tags: [
      "Portfolio",
      "Gallery",
      "WhatsApp",
      "Inquiry Form",
    ],
  },
  {
    id: 5,
    slug: "architect-portfolio",
    name: "Architect Portfolio",
    category: "architect-portfolio",
    subCategoryLabel: "Architect Portfolio",
    price: 15999,
    priceDisplay: "₹15,999",
    priceTier: "Up to 25 Pages",
    discount: 60,
    img: "/images/templates/interior/architect-portfolio.jpg",
    alt: "Professional Architect Portfolio Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "76",
    rating: "4.8",
    tags: [
      "Project Showcase",
      "Gallery",
      "CRM",
      "Contact Form",
    ],
  },
  {
    id: 6,
    slug: "interior-architect-firm",
    name: "Interior & Architect Firm",
    category: "interior-architect",
    subCategoryLabel: "Interior & Architecture",
    price: 17999,
    priceDisplay: "₹17,999",
    priceTier: "Up to 35 Pages",
    discount: 63,
    img: "/images/templates/interior/interior-architect.jpg",
    alt: "Interior and Architecture Firm Website",
    previewUrl: "https://themedekho.com/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "52",
    rating: "4.9",
    tags: [
      "Price Calculator",
      "CRM",
      "BOQ",
      "AI Chat Bot",
    ],
  },
];