import type { Product } from "@/types/product";

export const interiorProducts: Product[] = [
  {
    id: 1,
    slug: "decorpot",
    name: "Decorpot",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 68,
    img: "/images/templates/interior/interior1.webp",
    alt: "Decorpot Interior Design Website",
    previewUrl: "https://www.decorpot.com",
    badges: [
      // {
      //   type: "badge-sale",
      //   label: "68% Off",
      // },
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "98",
    rating: "4.8",
    tags: [
      "AI Chat Bot",
      "CRM",
      "Price Calculator",
      "BOQ",
    ],
  },
  {
    id: 2,
    slug: "gopesh-interior",
    name: "Gopesh Interior Furniture House",
    category: "interior-firm",
    subCategoryLabel: "Interior & Furniture",
    price: 9999,
    priceDisplay: "₹9,999",
    priceTier: "Up to 15 Pages",
    discount: 55,
    img: "/images/templates/interior/interior2.webp",
    alt: "Gopesh Interior Furniture House Website",
    previewUrl: "https://gifhouse.in",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "33",
    rating: "4.5",
    tags: [
      "AI Chat Bot",
      "CRM",
      "Price Calculator",
      "BOQ",
    ],
  },
  {
    id: 3,
    slug: "modern-architect-studio",
    name: "Modern Architect Studio",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 19999,
    priceDisplay: "₹19,999",
    priceTier: "Up to 40 Pages",
    discount: 61,
    img: "/images/templates/interior/architect.webp",
    alt: "Modern Architecture Studio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "67",
    rating: "4.9",
    tags: [
      "Project Gallery",
      "CRM",
      "Lead Form",
      "SEO",
    ],
  },
  {
    id: 4,
    slug: "interior-portfolio-pro",
    name: "Interior Portfolio Pro",
    category: "interior-portfolio",
    subCategoryLabel: "Interior Designer Portfolio",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 20 Pages",
    discount: 58,
    img: "/images/templates/interior/inter-portfolio.webp",
    alt: "Interior Designer Portfolio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-new",
        label: "New",
      },
    ],
    sold: "41",
    rating: "4.7",
    tags: [
      "Portfolio",
      "Gallery",
      "WhatsApp",
      "Inquiry Form",
    ],
  },
  {
    id: 5,
    slug: "architect-portfolio",
    name: "Architect Portfolio",
    category: "architect-portfolio",
    subCategoryLabel: "Architect Portfolio",
    price: 15999,
    priceDisplay: "₹15,999",
    priceTier: "Up to 25 Pages",
    discount: 60,
    img: "/images/theme.webp",
    alt: "Professional Architect Portfolio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "76",
    rating: "4.8",
    tags: [
      "Project Showcase",
      "Gallery",
      "CRM",
      "Contact Form",
    ],
  },
  {
    id: 6,
    slug: "interior-architect-firm",
    name: "Interior & Architect Firm",
    category: "interior-architect",
    subCategoryLabel: "Interior & Architecture",
    price: 17999,
    priceDisplay: "₹17,999",
    priceTier: "Up to 35 Pages",
    discount: 63,
    img: "/images/theme.webp",
    alt: "Interior and Architecture Firm Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "52",
    rating: "4.9",
    tags: [
      "Price Calculator",
      "CRM",
      "BOQ",
      "AI Chat Bot",
    ],
  },
  {
    id: 7,
    slug: "urban-space-interiors",
    name: "Urban Space Interiors",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 8999,
    priceDisplay: "₹8,999",
    priceTier: "Up to 15 Pages",
    discount: 50,
    img: "/images/templates/interior/interior3.webp",
    alt: "Urban Space Interiors Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "42",
    rating: "4.6",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 8,
    slug: "elite-home-interiors",
    name: "Elite Home Interiors",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 10999,
    priceDisplay: "₹10,999",
    priceTier: "Up to 20 Pages",
    discount: 56,
    img: "/images/templates/interior/interior4.webp",
    alt: "Elite Home Interiors Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "58",
    rating: "4.7",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 9,
    slug: "signature-interior-studio",
    name: "Signature Interior Studio",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 20 Pages",
    discount: 58,
    img: "/images/templates/interior/interior5.webp",
    alt: "Signature Interior Studio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "71",
    rating: "4.8",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 10,
    slug: "dreamline-interiors",
    name: "Dreamline Interiors",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 7999,
    priceDisplay: "₹7,999",
    priceTier: "Up to 12 Pages",
    discount: 45,
    img: "/images/templates/interior/interior6.webp",
    alt: "Dreamline Interiors Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "36",
    rating: "4.5",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 11,
    slug: "living-space-designs",
    name: "Living Space Designs",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 25 Pages",
    discount: 60,
    img: "/images/templates/interior/interior7.webp",
    alt: "Living Space Designs Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "83",
    rating: "4.8",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 12,
    slug: "prime-interior-solutions",
    name: "Prime Interior Solutions",
    category: "interior-firm",
    subCategoryLabel: "Interior Design",
    price: 11999,
    priceDisplay: "₹11,999",
    priceTier: "Up to 20 Pages",
    discount: 52,
    img: "/images/templates/interior/interior8.webp",
    alt: "Prime Interior Solutions Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "64",
    rating: "4.7",
    tags: ["AI Chat Bot", "CRM", "Price Calculator", "BOQ"],
  },
  {
    id: 13,
    slug: "axis-architects",
    name: "Axis Architects",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 13999,
    priceDisplay: "₹13,999",
    priceTier: "Up to 25 Pages",
    discount: 55,
    img: "/images/theme.webp",
    alt: "Axis Architects Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "49",
    rating: "4.7",
    tags: ["Project Gallery", "CRM", "Lead Form", "SEO"],
  },
  {
    id: 14,
    slug: "urban-arc-studio",
    name: "Urban Arc Studio",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 30 Pages",
    discount: 59,
    img: "/images/theme.webp",
    alt: "Urban Arc Studio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "62",
    rating: "4.8",
    tags: ["Project Gallery", "CRM", "Lead Form", "SEO"],
  },
  {
    id: 15,
    slug: "form-space-architects",
    name: "Form & Space Architects",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 18999,
    priceDisplay: "₹18,999",
    priceTier: "Up to 35 Pages",
    discount: 62,
    img: "/images/theme.webp",
    alt: "Form and Space Architects Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "74",
    rating: "4.9",
    tags: ["Project Gallery", "CRM", "Lead Form", "SEO"],
  },
  {
    id: 16,
    slug: "studio-vertex",
    name: "Studio Vertex",
    category: "architect-firm",
    subCategoryLabel: "Architecture Firm",
    price: 15999,
    priceDisplay: "₹15,999",
    priceTier: "Up to 30 Pages",
    discount: 57,
    img: "/images/theme.webp",
    alt: "Studio Vertex Architecture Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "55",
    rating: "4.7",
    tags: ["Project Gallery", "CRM", "Lead Form", "SEO"],
  },
  {
    id: 17,
    slug: "arc-and-interiors",
    name: "Arc & Interiors Studio",
    category: "interior-architect",
    subCategoryLabel: "Interior & Architecture",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 25 Pages",
    discount: 56,
    img: "/images/theme.webp",
    alt: "Arc and Interiors Studio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "47",
    rating: "4.7",
    tags: ["Price Calculator", "CRM", "BOQ", "AI Chat Bot"],
  },
  {
    id: 18,
    slug: "buildspace-designs",
    name: "BuildSpace Designs",
    category: "interior-architect",
    subCategoryLabel: "Interior & Architecture",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 30 Pages",
    discount: 60,
    img: "/images/theme.webp",
    alt: "BuildSpace Designs Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "59",
    rating: "4.8",
    tags: ["Price Calculator", "CRM", "BOQ", "AI Chat Bot"],
  },
  {
    id: 19,
    slug: "studio-integrate",
    name: "Studio Integrate",
    category: "interior-architect",
    subCategoryLabel: "Interior & Architecture",
    price: 18999,
    priceDisplay: "₹18,999",
    priceTier: "Up to 35 Pages",
    discount: 63,
    img: "/images/theme.webp",
    alt: "Studio Integrate Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "68",
    rating: "4.9",
    tags: ["Price Calculator", "CRM", "BOQ", "AI Chat Bot"],
  },
  {
    id: 20,
    slug: "minimal-interior-portfolio",
    name: "Minimal Interior Portfolio",
    category: "interior-portfolio",
    subCategoryLabel: "Interior Designer Portfolio",
    price: 8999,
    priceDisplay: "₹8,999",
    priceTier: "Up to 15 Pages",
    discount: 48,
    img: "/images/theme.webp",
    alt: "Minimal Interior Portfolio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "32",
    rating: "4.6",
    tags: ["Portfolio", "Gallery", "WhatsApp", "Inquiry Form"],
  },
  {
    id: 21,
    slug: "creative-interior-showcase",
    name: "Creative Interior Showcase",
    category: "interior-portfolio",
    subCategoryLabel: "Interior Designer Portfolio",
    price: 10999,
    priceDisplay: "₹10,999",
    priceTier: "Up to 20 Pages",
    discount: 54,
    img: "/images/theme.webp",
    alt: "Creative Interior Showcase Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "46",
    rating: "4.7",
    tags: ["Portfolio", "Gallery", "WhatsApp", "Inquiry Form"],
  },
  {
    id: 22,
    slug: "designer-portfolio-studio",
    name: "Designer Portfolio Studio",
    category: "interior-portfolio",
    subCategoryLabel: "Interior Designer Portfolio",
    price: 11999,
    priceDisplay: "₹11,999",
    priceTier: "Up to 20 Pages",
    discount: 57,
    img: "/images/theme.webp",
    alt: "Designer Portfolio Studio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "53",
    rating: "4.8",
    tags: ["Portfolio", "Gallery", "WhatsApp", "Inquiry Form"],
  },
  {
    id: 23,
    slug: "modern-architect-portfolio",
    name: "Modern Architect Portfolio",
    category: "architect-portfolio",
    subCategoryLabel: "Architect Portfolio",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 20 Pages",
    discount: 55,
    img: "/images/theme.webp",
    alt: "Modern Architect Portfolio Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "39",
    rating: "4.7",
    tags: ["Project Showcase", "Gallery", "CRM", "Contact Form"],
  },
  {
    id: 24,
    slug: "premium-architect-showcase",
    name: "Premium Architect Showcase",
    category: "architect-portfolio",
    subCategoryLabel: "Architect Portfolio",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 30 Pages",
    discount: 60,
    img: "/images/theme.webp",
    alt: "Premium Architect Showcase Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "57",
    rating: "4.8",
    tags: ["Project Showcase", "Gallery", "CRM", "Contact Form"],
  },
];