import type { ProductCardData, AdBannerData } from "@/types/product";

const commonPrice = { priceFrom: "₹4,999", priceTo: "₹19,999" };


export const interiorProducts: ProductCardData[] = [
  {
    id: 1,
    image: "/images/templates.jpg",
    bgColor: "#0E1730",
    category: "Interior",
    name: "Active Designs Pvt. Ltd.",
    sold: 124,
    rating: 4.8,
    reviewCount: 38,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
  {
    id: 2,
    image: "/images/templates.jpg",
    bgColor: "#0E1A33",
    category: "Architecture",
    name: "Arkin Designs",
    sold: 87,
    rating: 4.6,
    reviewCount: 24,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
  {
    id: 3,
    image: "/images/templates.jpg",
    bgColor: "#101B36",
    category: "Premium",
    categoryVariant: "hot",
    name: "D'LIFE Interiors",
    sold: 215,
    rating: 4.9,
    reviewCount: 67,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    previewName: "D'LIFE Interiors",
    ...commonPrice,
  },
  {
    id: 4,
    image: "/images/templates.jpg",
    bgColor: "#0E1A33",
    category: "Trending",
    categoryVariant: "hot",
    name: "Dream Home Studio (DHS)",
    sold: 193,
    rating: 4.7,
    reviewCount: 52,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
];

/** Healthcare cards ship with no preview image in the original HTML —
 *  the pc-img box just shows the background color + product name as text. */
export const healthcareProducts: ProductCardData[] = [
  {
    id: 1,
    bgColor: "#0B1730",
    category: "Eye Care",
    name: "Acuravision Eye Care",
    sold: 56,
    rating: 4.5,
    reviewCount: 18,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    previewName: "Acuravision",
    ...commonPrice,
  },
  {
    id: 2,
    bgColor: "#0A1830",
    category: "Hospital",
    name: "Amicare Orthopedic Hospital",
    sold: 142,
    rating: 4.8,
    reviewCount: 41,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    previewName: "Amicare Hospital",
    ...commonPrice,
  },
  {
    id: 3,
    bgColor: "#101B36",
    category: "Premium",
    categoryVariant: "hot",
    name: "Central Hospital West Delhi",
    sold: 98,
    rating: 4.7,
    reviewCount: 29,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    previewName: "Central Hospital",
    ...commonPrice,
  },
  {
    id: 4,
    bgColor: "#0A1224",
    category: "Cardiology",
    name: "Beheart Healthy",
    sold: 167,
    rating: 4.9,
    reviewCount: 55,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    previewName: "Beheart Healthy",
    ...commonPrice,
  },
];

export const ecommerceProducts: ProductCardData[] = [
  {
    id: 1,
    image: "/images/templates.jpg",
    bgColor: "#101B36",
    category: "Fashion",
    name: "6eDesign Fashion Store",
    sold: 73,
    rating: 4.6,
    reviewCount: 21,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
  {
    id: 2,
    image: "/images/templates.jpg",
    bgColor: "#141F38",
    category: "Jewellery",
    name: "Baijnath Jewellers",
    sold: 134,
    rating: 4.8,
    reviewCount: 44,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
  {
    id: 3,
    image: "/images/templates.jpg",
    bgColor: "#0B1628",
    category: "Popular",
    categoryVariant: "hot",
    name: "Joyalukkas",
    sold: 89,
    rating: 4.5,
    reviewCount: 27,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
  {
    id: 4,
    image: "/images/templates.jpg",
    bgColor: "#0A1224",
    category: "Fashion",
    name: "Kaya Designer Lounge",
    sold: 178,
    rating: 4.9,
    reviewCount: 61,
    previewUrl: "https://theme-dekho.github.io/development_page/",
    ...commonPrice,
  },
];

export const adBanners: Record<"interior" | "healthcare" | "ecommerce", AdBannerData> = {
  interior: {
    category: "interior",
    variant: "orange",
    tag: "Interior Special",
    titlePrefix: "Get Custom ",
    titleHighlight: "Interior & Architect",
    titleSuffix: " Website",
    oldPrice: "Starting ₹15,000",
    price: "₹9,999",
    discountLabel: "Save 33%",
  },
  healthcare: {
    category: "healthcare",
    variant: "green",
    tag: "Healthcare Special",
    titlePrefix: "Get Custom ",
    titleHighlight: "Healthcare",
    titleSuffix: " Website",
    oldPrice: "Starting ₹12,000",
    price: "₹7,999",
    discountLabel: "Save 33%",
    discountBg: "var(--green-dark)",
    btnBg: "var(--green-dark)",
    btnShadow: "0 6px 20px rgba(20,67,176,0.4)",
  },
  ecommerce: {
    category: "ecommerce",
    variant: "green",
    tag: "E-Commerce Special",
    titlePrefix: "Get Custom ",
    titleHighlight: "E-Commerce Store",
    titleSuffix: " + CRM + Payment Gateway",
    oldPrice: "Starting ₹18,000",
    price: "₹11,999",
    discountLabel: "Save 33%",
    discountBg: "var(--blue)",
    btnBg: "var(--blue)",
    btnShadow: "0 6px 20px rgba(37,99,235,0.4)",
  },
};
