import type { Product } from "@/types/product";

export const storeCategoryProducts: Product[] = [
  // =========================================================
  // ELECTRONICS STORE
  // =========================================================

  {
    id: 201,
    slug: "techzone-electronics",
    name: "TechZone Electronics",
    category: "electronics-store",
    subCategoryLabel: "Electronics Store",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 55,
    img: "/images/templates/ecommerce/techzone.webp",
    alt: "TechZone Electronics Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "124",
    rating: "4.8",
    tags: [
      "Electronics Products",
      "Product Catalogue",
      "Shopping Cart",
      "Online Payment",
    ],
  },

  {
    id: 202,
    slug: "digital-hub-store",
    name: "Digital Hub Store",
    category: "electronics-store",
    subCategoryLabel: "Electronics Store",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 35 Pages",
    discount: 58,
    img: "/images/templates/ecommerce/digitalhub.webp",
    alt: "Digital Hub Electronics Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "96",
    rating: "4.7",
    tags: [
      "Mobile Products",
      "Laptop Products",
      "Product Filters",
      "Wishlist",
    ],
  },

  {
    id: 203,
    slug: "smartcart-electronics",
    name: "SmartCart Electronics",
    category: "electronics-store",
    subCategoryLabel: "Electronics Store",
    price: 18999,
    priceDisplay: "₹18,999",
    priceTier: "Up to 40 Pages",
    discount: 60,
    img: "/images/templates/ecommerce/smartcart.webp",
    alt: "SmartCart Electronics Ecommerce Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "142",
    rating: "4.9",
    tags: [
      "Electronics Ecommerce",
      "Product Variations",
      "Checkout",
      "Customer Account",
    ],
  },

  {
    id: 204,
    slug: "gadget-point-store",
    name: "Gadget Point Store",
    category: "electronics-store",
    subCategoryLabel: "Electronics Store",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 25 Pages",
    discount: 52,
    img: "/images/templates/ecommerce/gadgetpoint.webp",
    alt: "Gadget Point Electronics Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "73",
    rating: "4.6",
    tags: [
      "Gadgets",
      "Accessories",
      "Product Search",
      "Online Orders",
    ],
  },

  // =========================================================
  // GROCERIES STORE
  // =========================================================

  {
    id: 205,
    slug: "freshbasket-grocery",
    name: "FreshBasket Grocery",
    category: "groceries-store",
    subCategoryLabel: "Groceries Store",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 25 Pages",
    discount: 50,
    img: "/images/templates/ecommerce/freshbasket.webp",
    alt: "FreshBasket Grocery Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "138",
    rating: "4.8",
    tags: [
      "Grocery Products",
      "Fresh Produce",
      "Shopping Cart",
      "Online Orders",
    ],
  },

  {
    id: 206,
    slug: "daily-mart-store",
    name: "Daily Mart Store",
    category: "groceries-store",
    subCategoryLabel: "Groceries Store",
    price: 13999,
    priceDisplay: "₹13,999",
    priceTier: "Up to 28 Pages",
    discount: 53,
    img: "/images/templates/ecommerce/dailymart.webp",
    alt: "Daily Mart Grocery Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "101",
    rating: "4.7",
    tags: [
      "Daily Essentials",
      "Product Categories",
      "Wishlist",
      "Checkout",
    ],
  },

  {
    id: 207,
    slug: "organic-basket",
    name: "Organic Basket",
    category: "groceries-store",
    subCategoryLabel: "Groceries Store",
    price: 15999,
    priceDisplay: "₹15,999",
    priceTier: "Up to 30 Pages",
    discount: 56,
    img: "/images/templates/ecommerce/organicbasket.webp",
    alt: "Organic Basket Grocery Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "87",
    rating: "4.8",
    tags: [
      "Organic Products",
      "Healthy Food",
      "Product Filters",
      "Online Payment",
    ],
  },

  {
    id: 208,
    slug: "quick-grocery-store",
    name: "Quick Grocery Store",
    category: "groceries-store",
    subCategoryLabel: "Groceries Store",
    price: 11999,
    priceDisplay: "₹11,999",
    priceTier: "Up to 20 Pages",
    discount: 48,
    img: "/images/templates/ecommerce/quickgrocery.webp",
    alt: "Quick Grocery Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "69",
    rating: "4.6",
    tags: [
      "Food Products",
      "Daily Needs",
      "Product Search",
      "Order Management",
    ],
  },

  // =========================================================
  // HOME & FURNITURE STORE
  // =========================================================

  {
    id: 209,
    slug: "urban-home-furniture",
    name: "Urban Home Furniture",
    category: "home-furniture-store",
    subCategoryLabel: "Home & Furniture Store",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 30 Pages",
    discount: 57,
    img: "/images/templates/ecommerce/urbanhome.webp",
    alt: "Urban Home Furniture Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "112",
    rating: "4.8",
    tags: [
      "Furniture Catalogue",
      "Home Decor",
      "Product Categories",
      "Wishlist",
    ],
  },

  {
    id: 210,
    slug: "living-space-furniture",
    name: "Living Space Furniture",
    category: "home-furniture-store",
    subCategoryLabel: "Home & Furniture Store",
    price: 18999,
    priceDisplay: "₹18,999",
    priceTier: "Up to 35 Pages",
    discount: 60,
    img: "/images/templates/ecommerce/livingspace.webp",
    alt: "Living Space Furniture Ecommerce Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "126",
    rating: "4.9",
    tags: [
      "Premium Furniture",
      "Product Variations",
      "Shopping Cart",
      "Online Payment",
    ],
  },

  {
    id: 211,
    slug: "comfort-home-store",
    name: "Comfort Home Store",
    category: "home-furniture-store",
    subCategoryLabel: "Home & Furniture Store",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 28 Pages",
    discount: 54,
    img: "/images/templates/ecommerce/comforthome.webp",
    alt: "Comfort Home Furniture Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "84",
    rating: "4.7",
    tags: [
      "Living Room Furniture",
      "Bedroom Furniture",
      "Home Furnishing",
      "Checkout",
    ],
  },

  {
    id: 212,
    slug: "woodcraft-furniture",
    name: "WoodCraft Furniture",
    category: "home-furniture-store",
    subCategoryLabel: "Home & Furniture Store",
    price: 19999,
    priceDisplay: "₹19,999",
    priceTier: "Up to 40 Pages",
    discount: 61,
    img: "/images/templates/ecommerce/woodcraft.webp",
    alt: "WoodCraft Furniture Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "95",
    rating: "4.8",
    tags: [
      "Wood Furniture",
      "Custom Furniture",
      "Product Catalogue",
      "Customer Account",
    ],
  },

  // =========================================================
  // APPAREL & FASHION STORE
  // =========================================================

  {
    id: 213,
    slug: "stylehub-fashion",
    name: "StyleHub Fashion",
    category: "apparel-fashion-store",
    subCategoryLabel: "Apparel & Fashion Store",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 30 Pages",
    discount: 55,
    img: "/images/templates/ecommerce/stylehub.webp",
    alt: "StyleHub Apparel and Fashion Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "147",
    rating: "4.8",
    tags: [
      "Fashion Products",
      "Clothing Catalogue",
      "Product Variations",
      "Wishlist",
    ],
  },

  {
    id: 214,
    slug: "urban-wear-store",
    name: "Urban Wear Store",
    category: "apparel-fashion-store",
    subCategoryLabel: "Apparel & Fashion Store",
    price: 15999,
    priceDisplay: "₹15,999",
    priceTier: "Up to 30 Pages",
    discount: 56,
    img: "/images/templates/ecommerce/urbanwear.webp",
    alt: "Urban Wear Fashion Ecommerce Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "108",
    rating: "4.7",
    tags: [
      "Streetwear",
      "Fashion Store",
      "Size Variations",
      "Online Payment",
    ],
  },

  {
    id: 215,
    slug: "luxury-fashion-boutique",
    name: "Luxury Fashion Boutique",
    category: "apparel-fashion-store",
    subCategoryLabel: "Apparel & Fashion Store",
    price: 19999,
    priceDisplay: "₹19,999",
    priceTier: "Up to 40 Pages",
    discount: 62,
    img: "/images/templates/ecommerce/luxury.webp",
    alt: "Luxury Fashion Boutique Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "121",
    rating: "4.9",
    tags: [
      "Luxury Fashion",
      "Designer Clothing",
      "Product Filters",
      "Customer Account",
    ],
  },

  {
    id: 216,
    slug: "trendline-apparel",
    name: "Trendline Apparel",
    category: "apparel-fashion-store",
    subCategoryLabel: "Apparel & Fashion Store",
    price: 12999,
    priceDisplay: "₹12,999",
    priceTier: "Up to 25 Pages",
    discount: 51,
    img: "/images/templates/ecommerce/trendline.webp",
    alt: "Trendline Apparel Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "72",
    rating: "4.6",
    tags: [
      "Apparel",
      "Casual Wear",
      "Shopping Cart",
      "Checkout",
    ],
  },

  // =========================================================
  // JEWELRY STORE
  // =========================================================

  {
    id: 217,
    slug: "royal-jewels-store",
    name: "Royal Jewels Store",
    category: "jewelry-store",
    subCategoryLabel: "Jewelry Store",
    price: 18999,
    priceDisplay: "₹18,999",
    priceTier: "Up to 35 Pages",
    discount: 60,
    img: "/images/templates/ecommerce/royal.webp",
    alt: "Royal Jewels Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "132",
    rating: "4.9",
    tags: [
      "Gold Jewelry",
      "Diamond Jewelry",
      "Product Catalogue",
      "Online Payment",
    ],
  },

  {
    id: 218,
    slug: "diamond-gallery",
    name: "Diamond Gallery",
    category: "jewelry-store",
    subCategoryLabel: "Jewelry Store",
    price: 20999,
    priceDisplay: "₹20,999",
    priceTier: "Up to 40 Pages",
    discount: 63,
    img: "/images/templates/ecommerce/diamond.webp",
    alt: "Diamond Gallery Jewelry Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-premium",
        label: "Premium",
      },
    ],
    sold: "118",
    rating: "4.9",
    tags: [
      "Diamond Jewelry",
      "Luxury Jewelry",
      "Product Variations",
      "Wishlist",
    ],
  },

  {
    id: 219,
    slug: "ornament-house",
    name: "Ornament House",
    category: "jewelry-store",
    subCategoryLabel: "Jewelry Store",
    price: 16999,
    priceDisplay: "₹16,999",
    priceTier: "Up to 30 Pages",
    discount: 57,
    img: "/images/templates/ecommerce/ornament.webp",
    alt: "Ornament House Jewelry Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [
      {
        type: "badge-hot",
        label: "Popular",
      },
    ],
    sold: "97",
    rating: "4.8",
    tags: [
      "Gold Ornaments",
      "Fashion Jewelry",
      "Product Categories",
      "Checkout",
    ],
  },

  {
    id: 220,
    slug: "elegance-jewellery",
    name: "Elegance Jewellery",
    category: "jewelry-store",
    subCategoryLabel: "Jewelry Store",
    price: 14999,
    priceDisplay: "₹14,999",
    priceTier: "Up to 25 Pages",
    discount: 55,
    img: "/images/templates/ecommerce/elegance.webp",
    alt: "Elegance Jewellery Store Website",
    previewUrl: "https://theme-dekho.github.io/development_page/",
    badges: [],
    sold: "79",
    rating: "4.7",
    tags: [
      "Jewelry",
      "Earrings",
      "Necklaces",
      "Shopping Cart",
    ],
  },
];