// import type { Metadata } from "next";
// import { Inter, Sora } from "next/font/google";
// import "./globals.css";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// const sora = Sora({
//   subsets: ["latin"],
//   variable: "--font-sora",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" 
//     suppressHydrationWarning 
//     className={`${inter.variable} ${sora.variable} h-full antialiased`}>
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

export default function AIBuilderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className="min-h-full flex flex-col"
      suppressHydrationWarning
    >
      <main className="flex-1">
        {children}
      </main>
    </div>
  );
}
